/////////////////////////////////////////user////////////////////////////////////////////////////////////////////////
###
GET https://localhost:5050/user/ HTTP/1.1

###
DELETE https://localhost:5050/user/ HTTP/1.1
Content-Type: application/json

{
"name": "test9",
"position": "youwillneverguess",
"level": "senior"
}

###
POST https://localhost:5050/user/signup HTTP/1.1
Content-Type: application/json

{
"name": "newuser123",
"password": "password123"
}

###
POST http://localhost:5050/user/login HTTP/1.1
Content-Type: application/json

{
"name": "newuser123",
"password": "password123"
}

//////////////////////////////////////records/////////////////////////////////////////////////////

###
POST https://localhost:5050/record HTTP/1.1
Content-Type: application/application/json

{
    "name" : "record"
}

###
DELETE https://localhost:5050/record/651d6c41b4527c4d9518422c HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6ImRvbnRGb3JnZXQiLCJpYXQiOjE2OTY4NDM1MjksImV4cCI6MTY5Njg0NzEyOX0.nAwY3oqAWz0Yj1VtH5pZwpC_J3eBomk0i8t2aS6l2SE

###
POST http://localhost:5050/record/create HTTP/1.1
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6InBhc3N3b3JkMTIzIiwiaWF0IjoxNjk5Mjc0OTU0LCJleHAiOjE2OTkyNzg1NTR9.Gdu4VMPheksAm48-pL_PJ-kI7SUkY6zsbRUUoEQeWUY

{
    "name":"priyanka",
    "position": 2,
    "level": 100
}